---
- name: Start frontend container
  community.docker.docker_container:
    name: front
    image: tp1_docker_app-front
    state: started
    restart_policy: unless-stopped
    ports:
      - "8081:80"
    networks:
      - tp1_net