---
- name: Deploy app sources
  ansible.builtin.copy:
    src: app/
    dest: /opt/app/
    mode: "0755"

- name: Build backend image
  community.docker.docker_image:
    name: tp1_docker_app-backend
    build:
      path: /opt/app/backend
    source: build
    force_source: true

- name: Build frontend image
  community.docker.docker_image:
    name: tp1_docker_app-front
    build:
      path: /opt/app/front
    source: build
    force_source: true