name: Build and Push Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: ./simpleapi
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simpleapi:latest

      - name: Build db
        uses: docker/build-push-action@v6
        with:
          context: ./db
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      - name: Build httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest