name: CI devops 2026

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # Downloads your repository code into the GitHub runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Installs Java 21 so Maven can build the project
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Builds the backend and runs unit/integration tests
      - name: Build and test with Maven
        run: mvn clean verify --file ./simpleapi/pom.xml

      # Runs SonarCloud analysis after tests
      - name: SonarCloud analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=stackOverSwag_DevOpsMLOps -Dsonar.organization=stackoverswag -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./simpleapi/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      # Downloads your repository code into the GitHub runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Logs in to Docker Hub using GitHub repository secrets
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Enables Docker Buildx for modern builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Builds and pushes the backend image
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simpleapi
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simpleapi:latest

      # Builds and pushes the database image
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./db
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      # Builds and pushes the http server image
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest